name: "UHPPOTE MQTT"
description: "UHPPOTE to MQTT bridge"
version: "1.0.0"
slug: "uhppote"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  uhppote_device_id: int
  name: str
  door: int
  mqtt_id: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  base_topic: str
options:
  uhppote_device_id: null
  name: null
  door: 1
  mqtt_id: "uhppote-gate"
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_username: null
  mqtt_password: null
  base_topic: "homeassistant/lock/uhppote"

